
import java.awt.FileDialog;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kj
 */
public class UDPRECIEVER extends javax.swing.JFrame {

    /**
     * Creates new form UDPRECIEVER
     */
    DatagramSocket ds;
    DatagramPacket dp;
    byte b[]=new byte[1028744];
    private String ms;
    int ar[][]=new int[15][15];
    int st=137;
    String data;

    public UDPRECIEVER() {
        try
        {
        initComponents();
        ds=new DatagramSocket(3012);
        }
         catch(Exception ex){}
        ar[0][0]=67;  
ar[0][1]= 114;
ar[0][2]= 121;
ar[0][3]= 112;
ar[0][4]= 84;
ar[0][5]= 79;
ar[0][6]= 71;
ar[0][7]= 82;
ar[0][8]= 97;
ar[0][9]= 80;
ar[0][10]= 72;
ar[0][11]= 89;
ar[0][12]= 32;
ar[0][13]= 33;
ar[0][14]= 34;
ar[1][0]= 35;
ar[1][1]= 36;
ar[1][2]= 37;
ar[1][3]= 38;
ar[1][4]= 39;
ar[1][5]= 40;
ar[1][6]= 41;
ar[1][7]= 42;
ar[1][8]= 43;
ar[1][9]= 44;
ar[1][9]= 44;
ar[1][10]= 45;
ar[1][11]= 46;
ar[1][12]= 47;
ar[1][13]= 48;
ar[1][14]= 49;
ar[2][0]= 50;
ar[2][1]= 51;
ar[2][2]= 52;
ar[2][3]= 53;
ar[2][4]= 54;
ar[2][5]= 55;
ar[2][6]=56;
ar[2][7]= 57;
ar[2][8]= 58;
ar[2][9]= 59;
ar[2][10]= 60;
ar[2][11]= 61;
ar[2][12]= 62;
ar[2][13]= 63;
ar[2][14]= 64;
ar[3][0]= 65;
ar[3][1]= 66;
ar[3][2]= 68;
ar[3][3]= 69;
ar[3][4]= 70;
ar[3][5]= 73;
ar[3][6]= 74;
ar[3][7]=75;
ar[3][8]= 76;
ar[3][9]= 77;
ar[3][10]= 78;
ar[3][11]= 81;
ar[3][12]= 83;
ar[3][13]= 85;
ar[3][14]= 86;
ar[4][0]= 87;
ar[4][1]= 88;
ar[4][2]= 90;
ar[4][3]= 91;
ar[4][4]= 92;
ar[4][5]= 93;
ar[4][6]= 94;
ar[4][7]= 95;
ar[4][8]= 96;
ar[4][9]= 98;
ar[4][10]= 99;
ar[4][11]= 100;
ar[4][12]= 101;
ar[4][13]= 102;
ar[4][14]= 103;
ar[5][0]= 104;
ar[5][1]= 105;
ar[5][2]= 106;
ar[5][3]= 107;
ar[5][4]= 108;
ar[5][5]= 109;
ar[5][6]= 110;
ar[5][7]= 111;
ar[5][8]= 113;
ar[5][9]= 115;
ar[5][10]= 116;
ar[5][11]= 117;
ar[5][12]= 118;
ar[5][13]= 119;
ar[5][14]= 120;
ar[6][0]= 122;
ar[6][1]= 123;
ar[6][2]= 124;
ar[6][3]= 125;
ar[6][4]= 126;
ar[6][5]= 127;
ar[6][6]= 128;
ar[6][7]= 129;
ar[6][8]= 130;
ar[6][9]= 131;
ar[6][10]= 132;
ar[6][11]= 133;
ar[6][12]= 134;
ar[6][13]= 135;
ar[6][14]= 136;


       for(int i=7;i<=14;i++)
        {
            for(int j=0;j<=14;j++)
            {
                if(st==257)
                    break;
                ar[i][j]=st++;
               // System.out.println("ar["+i+"]["+j+"]= "+(char)ar[i][j]);
            }
        }
       for(int i=0;i<=14;i++)
        {
            for(int j=0;j<=14;j++)
            {
                
               System.out.println("ar["+i+"]["+j+"]= "+(char)ar[i][j]+"\tvalue="+ar[i][j]);
            }
        }

        
    }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        RECIEVE = new javax.swing.JButton();
        DECRYPT = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta.setBackground(new java.awt.Color(55, 125, 22));
        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        RECIEVE.setText("RECIEVE");
        RECIEVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECIEVEActionPerformed(evt);
            }
        });

        DECRYPT.setText("DECRYPT");
        DECRYPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECRYPTActionPerformed(evt);
            }
        });

        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CLEAR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RECIEVE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(SAVE))
                            .addComponent(DECRYPT))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(RECIEVE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(DECRYPT)
                        .addGap(61, 61, 61)
                        .addComponent(CLEAR)))
                .addGap(36, 36, 36)
                .addComponent(SAVE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RECIEVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECIEVEActionPerformed
        // TODO add your handling code here:
        try
        {
            dp=new DatagramPacket(b,b.length);
            ds.receive(dp);
            ms=new String(dp.getData(),0,dp.getLength());
            ta.setText(ms);
            System.out.println(ms.length());
            System.out.println(new String(b));
        
        }catch(IOException ex){}
        
    }//GEN-LAST:event_RECIEVEActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        ta.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
       FileOutputStream fos=null;
       FileDialog fd=new FileDialog(this,"save",FileDialog.SAVE);
       fd.show();
       try
       {
           fos=new FileOutputStream(fd.getDirectory()+fd.getFile());
           
       }catch(Exception ex){}
       try
       {
           fos.write(b);
       }catch(Exception ex){}
    }//GEN-LAST:event_SAVEActionPerformed

    private void DECRYPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECRYPTActionPerformed
        // TODO add your handling code here:
       int p1=0,p2=0,p3=0,p4=0;
      System.out.println(b.length);
        for(int r=0;r<ms.length();r+=2)
        {
                for(int i=0;i<=14;i++)
                {
                    for(int j=0;j<=14;j++)
                    {
                        if(b[r]==ar[i][j])
                        {
                            p1=i;p2=j;
                        }
                        if(b[r+1]==ar[i][j])
                        {
                            p3=i;p4=j;
                        }
                    }
                }
                if(p1==p3)
                {
                    int ip2=p2-1,ip4=p4-1;
                    if(ip2==-1)
                        ip2=14;
                    if(ip4==-1)
                        ip4=14;
                    b[r]=(byte)ar[p1][ip2];
                    b[r+1]=(byte)ar[p3][ip4];
                    
                    
                }
                else if(p2==p4)
                {
                    int ip1=p1-1,ip3=p3-1;
                    if(ip1==-1)
                        ip1=14;
                    if(ip3==-1)
                        ip3=14;
                    
                    b[r]=(byte)ar[ip1][p2];
                    b[r+1]=(byte)ar[ip3][p4];
                    
                }
                else
                {
                    b[r]=(byte)ar[p1][p4];
                    b[r+1]=(byte)ar[p3][p2];
                }
                
        } 
        System.out.println(new String(b));
        ta.setText(new String(b));
 
        
        
        
        
    }//GEN-LAST:event_DECRYPTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UDPRECIEVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UDPRECIEVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UDPRECIEVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UDPRECIEVER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UDPRECIEVER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DECRYPT;
    private javax.swing.JButton RECIEVE;
    private javax.swing.JButton SAVE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
